### ISSUE TITLE
Flux panics when k8s-allow-namespace=""

### ISSUE THREAD

**Issue by sklemmer** [fluxcd/flux#2396]
**Describe the bug**
When running flux with --k8s-allow-namespace="" argument it panics right after start

```ts=2019-08-22T12:23:40.430044949Z caller=checkpoint.go:24 component=checkpoint msg="up to date" latest=1.13.3
panic: assignment to entry in nil map

goroutine 66 [running]:
github.com/weaveworks/flux/cluster/kubernetes.(*helmReleaseKind).getWorkloads(0x286b410, 0x1aeee60, 0xc000044070, 0xc00053ee00, 0xc00046c234, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/resourcekinds.go:518 +0x165
github.com/weaveworks/flux/cluster/kubernetes.(*Cluster).ImagesToFetch(0xc00053ee00, 0x0)
	/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/images.go:137 +0x76f
github.com/weaveworks/flux/registry.ImageCredsWithAWSAuth.func5(0xdf8475800)
	/home/circleci/go/src/github.com/weaveworks/flux/registry/aws.go:211 +0x8d
github.com/weaveworks/flux/registry/cache.(*Warmer).Loop(0xc0003af180, 0x1ab9100, 0xc000019cb0, 0xc00013e0c0, 0xc0004572d0, 0xc000098960)
	/home/circleci/go/src/github.com/weaveworks/flux/registry/cache/warming.go:83 +0x90
created by main.main
	/home/circleci/go/src/github.com/weaveworks/flux/cmd/fluxd/main.go:724 +0x635f
```

**To Reproduce**
In our setup we deploy flux in every namespace with --k8s-allow-namespace="$NAMESPACE" by using a flux in namespace _flux-system_.
This one is deployed using terraform and therefore deployed with --k8s-allow-namespace=""

**Expected behavior**
Flux runs without error like in 1.13.3

**Logs**
```
ts=2019-08-22T12:26:37.709249147Z caller=main.go:232 version=1.14.0
ts=2019-08-22T12:26:37.709296039Z caller=main.go:361 msg="using in cluster config to connect to the cluster"
ts=2019-08-22T12:26:37.811388262Z caller=main.go:446 component=cluster identity=/etc/fluxd/ssh/identity
ts=2019-08-22T12:26:37.811426321Z caller=main.go:447 component=cluster identity.pub="ssh-rsa xxx "
ts=2019-08-22T12:26:37.811452249Z caller=main.go:452 host=https://172.20.0.1:443 version=kubernetes-v1.13.8-eks-a977ba
ts=2019-08-22T12:26:37.811496392Z caller=main.go:464 kubectl=/usr/local/bin/kubectl
ts=2019-08-22T12:26:37.812204231Z caller=main.go:476 ping=true
ts=2019-08-22T12:26:37.816425415Z caller=main.go:612 url=git@example.de:user/flux-system.git user="Weave Flux" email=support@weave.works signing-key= verify-signatures=false sync-tag=integration state=git readonly=false notes-ref=integration set-author=false git-secret=false
ts=2019-08-22T12:26:37.816475171Z caller=main.go:713 upstream="no upstream URL given"
ts=2019-08-22T12:26:37.817915061Z caller=main.go:742 metrics-addr=:3031
ts=2019-08-22T12:26:37.884189542Z caller=loop.go:100 component=sync-loop err="git repo not ready: git repo has not been cloned yet"
ts=2019-08-22T12:26:37.884247304Z caller=images.go:17 component=sync-loop msg="polling for new images for automated workloads"
ts=2019-08-22T12:26:37.884260364Z caller=images.go:27 component=sync-loop msg="no automated workloads"
ts=2019-08-22T12:26:37.885376083Z caller=main.go:734 addr=:3030
panic: assignment to entry in nil map

goroutine 56 [running]:
github.com/weaveworks/flux/cluster/kubernetes.(*helmReleaseKind).getWorkloads(0x286b410, 0x1aeee60, 0xc000044070, 0xc0001b6e00, 0xc001a8feb4, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/resourcekinds.go:518 +0x165
github.com/weaveworks/flux/cluster/kubernetes.(*Cluster).ImagesToFetch(0xc0001b6e00, 0x0)
	/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/images.go:137 +0x76f
github.com/weaveworks/flux/registry.ImageCredsWithAWSAuth.func5(0xdf8475800)
	/home/circleci/go/src/github.com/weaveworks/flux/registry/aws.go:211 +0x8d
github.com/weaveworks/flux/registry/cache.(*Warmer).Loop(0xc00057c040, 0x1ab9100, 0xc000391440, 0xc0000865a0, 0xc00066a830, 0xc00013b4f0)
	/home/circleci/go/src/github.com/weaveworks/flux/registry/cache/warming.go:83 +0x90
created by main.main
	/home/circleci/go/src/github.com/weaveworks/flux/cmd/fluxd/main.go:724 +0x635f
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.14.0
- Helm Operator version: 1.0.0-rc1
- Kubernetes version: v1.13.8-eks-cd3eb0
- Git provider: Gitlab
- Container registry provider: Dockerhub

**Comment by hiddeco** [comment]
Comparing the crash logs and using common sense, it looks like this got resolved in #2404.

**Comment by sklemmer** [comment]
Thats awesome thank you :+1:

**Comment by bforchhammer** [comment]
I am afraid I'm still receiving the same error on v1.14.1.

```
ts=2019-08-23T15:32:22.599468923Z caller=main.go:232 version=1.14.1
...
ts=2019-08-23T15:32:22.639077625Z caller=images.go:27 component=sync-loop msg="no automated workloads"
panic: assignment to entry in nil map
 goroutine 66 [running]:
github.com/weaveworks/flux/cluster/kubernetes.(*helmReleaseKind).getWorkloads(0x286b410, 0x1aeee80, 0xc000044070, 0xc0000ec300, 0xc0001018e4, 0x9, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/resourcekinds.go:518 +0x165
github.com/weaveworks/flux/cluster/kubernetes.(*Cluster).ImagesToFetch(0xc0000ec300, 0x0)
	/home/circleci/go/src/github.com/weaveworks/flux/cluster/kubernetes/images.go:137 +0x76f
github.com/weaveworks/flux/registry.ImageCredsWithAWSAuth.func5(0xdf8475800)
	/home/circleci/go/src/github.com/weaveworks/flux/registry/aws.go:211 +0x8d
github.com/weaveworks/flux/registry/cache.(*Warmer).Loop(0xc0004d8b80, 0x1ab9120, 0xc0005f3fb0, 0xc0000865a0, 0xc000101010, 0xc0001187d0)
	/home/circleci/go/src/github.com/weaveworks/flux/registry/cache/warming.go:83 +0x90
created by main.main
	/home/circleci/go/src/github.com/weaveworks/flux/cmd/fluxd/main.go:724 +0x635f
```

I'm not expert with go, but I think the `0` in `names := make(map[string]bool, 0)` means it's initialized to size `0`; the [golang docs on make](https://golang.org/pkg/builtin/#make) indicate that the size could also be omitted, so maybe just `names := make(map[string]bool)`?

**Comment by sklemmer** [comment]
@bforchhammer Its merged but was not part of the 1.14.1 release
https://github.com/fluxcd/flux/blob/1.14.1/cluster/kubernetes/resourcekinds.go#L512

**Comment by bforchhammer** [comment]
@sklemmer Yes, I eventually realized that as well! :wink: Glad to see it's fixed already and looking forward to the next release! :-)
